## ALEXANDER VILLATORO 1182118  11/4/2021 

In [1]:
import numpy as np
import pandas as pd
data = np.random.seed(2131982)
data = np.random.randint(1,101, size=(10, 10))
print(data)
print("Media aritmetica")
print("La media aritmetica de la matriz es", data.mean())
print("")
print("Mediana")
print("La mediana de la matriz es", np.median(data))
print("")
print("Desviación típica")
print("La desviación típica de la matriz es", data.std())
print("")
print("Varianza")
print("La varianza de la matriz es", data.var())
print("")

[[  2   3  48  59  89  79  71  80  19  22]
 [ 74  20  16  13  74  88  61  28  11  79]
 [ 86  91  91  80  43   6  83  59 100  98]
 [ 38  37  47  48  15  17  21   6  32  88]
 [ 14  18  54  39  47  48  33  59  63  49]
 [ 98  19  59  99  26  42  77  62  25  11]
 [ 42  25  16  66   6  76  84  20  11  95]
 [  9  27  63  24  15  73  44  22  47  85]
 [ 58  37  94  24  99  70  39  46  29 100]
 [ 98  92  91  24  70  91  78  73  73  37]]
Media aritmetica
La media aritmetica de la matriz es 51.37

Mediana
La mediana de la matriz es 48.0

Desviación típica
La desviación típica de la matriz es 29.729330634913392

Varianza
La varianza de la matriz es 883.8331



In [2]:
print("Media aritmética de cada fila")
for i,fila in enumerate(data): #for de cada fila
    print("La media aritmetica de cada fila es",i,fila.mean())
print("")
print("Media aritmética de cada columna")
suma = 0
for j, columna in enumerate(data):
    for k, fila in enumerate(columna):
        if k == 9:
            suma += data[k][j]
            print("La media aritmética de cada columna", j , suma/10)
            suma = 0
        else:
            suma += data[k][j]
print("")
print("Desviación típica de cada fila")
for i,fila in enumerate(data): #for de cada fila
    print("La desviación típica de cada fila es",i,fila.std())            
print("")
print("Desviación típica de cada columna")
listaSuma = list()
for j, columna in enumerate(data):
    for k, fila in enumerate(columna):
        if k == 9:
            listaSuma.append(data[k][j])
            arr = np.array(listaSuma)
            print("La desviación típica de cada columna", j , arr.std())
            listaSuma.clear()
        else:
            listaSuma.append(data[k][j])

Media aritmética de cada fila
La media aritmetica de cada fila es 0 47.2
La media aritmetica de cada fila es 1 46.4
La media aritmetica de cada fila es 2 73.7
La media aritmetica de cada fila es 3 34.9
La media aritmetica de cada fila es 4 42.4
La media aritmetica de cada fila es 5 51.8
La media aritmetica de cada fila es 6 44.1
La media aritmetica de cada fila es 7 40.9
La media aritmetica de cada fila es 8 59.6
La media aritmetica de cada fila es 9 72.7

Media aritmética de cada columna
La media aritmética de cada columna 0 51.9
La media aritmética de cada columna 1 36.9
La media aritmética de cada columna 2 57.9
La media aritmética de cada columna 3 47.6
La media aritmética de cada columna 4 48.4
La media aritmética de cada columna 5 59.0
La media aritmética de cada columna 6 59.1
La media aritmética de cada columna 7 45.5
La media aritmética de cada columna 8 41.0
La media aritmética de cada columna 9 66.4

Desviación típica de cada fila
La desviación típica de cada fila es 0 31.57

In [3]:
print("Varianza de cada fila")
for i,fila in enumerate(data): #for de cada fila
    print("La Varianza de cada fila es",i,fila.var())            
print("")
print("Varianza de cada columna")
listaSuma = list()
for j, columna in enumerate(data):
    for k, fila in enumerate(columna):
        if k == 9:
            listaSuma.append(data[k][j])
            arr = np.array(listaSuma)
            print("La desviación típica de cada columna", j , arr.var())
            listaSuma.clear()
        else:
            listaSuma.append(data[k][j])

Varianza de cada fila
La Varianza de cada fila es 0 996.76
La Varianza de cada fila es 1 885.8399999999999
La Varianza de cada fila es 2 790.0099999999999
La Varianza de cada fila es 3 490.48999999999995
La Varianza de cada fila es 4 243.24
La Varianza de cada fila es 5 937.36
La Varianza de cada fila es 6 996.6900000000002
La Varianza de cada fila es 7 603.49
La Varianza de cada fila es 8 780.2400000000001
La Varianza de cada fila es 9 536.4100000000001

Varianza de cada columna
La desviación típica de cada columna 0 1199.6899999999998
La desviación típica de cada columna 1 831.49
La desviación típica de cada columna 2 726.49
La desviación típica de cada columna 3 710.24
La desviación típica de cada columna 4 989.24
La desviación típica de cada columna 5 785.4
La desviación típica de cada columna 6 477.89
La desviación típica de cada columna 7 565.25
La desviación típica de cada columna 8 779.0
La desviación típica de cada columna 9 1012.4399999999999


In [4]:
dm = pd.DataFrame(data)
dm.describe()

0          1          2          3          4          5  \
count  10.00000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   51.90000  36.900000  57.900000  47.600000  48.400000  59.000000   
std    36.51012  30.395358  28.411461  28.091913  33.153515  29.540932   
min     2.00000   3.000000  16.000000  13.000000   6.000000   6.000000   
25%    20.00000  19.250000  47.250000  24.000000  17.750000  43.500000   
50%    50.00000  26.000000  56.500000  43.500000  45.000000  71.500000   
75%    83.00000  37.000000  84.000000  64.250000  73.000000  78.250000   
max    98.00000  92.000000  94.000000  99.000000  99.000000  91.000000   

               6          7           8           9  
count  10.000000  10.000000   10.000000   10.000000  
mean   59.100000  45.500000   41.000000   66.400000  
std    23.043196  25.061037   29.420326   33.540026  
min    21.000000   6.000000   11.000000   11.000000  
25%    40.250000  23.500000   20.500000   40.000000  
50%    66.000000  52.500000   30.500000   82.000000  
75%    77.750000  61.250000   59.000000   93.250000  
max    84.000000  80.000000  100.000000  100.000000

## ¿Son coherentes los datos entre Numpy y Pandas?
En el caso de la media los datos se son coherentes, si se tiene una relacion entre si, pero en el caso de std(Desviación típica) se da a notas que los datos no son conherentes, ya que existe una diferencia de entre el .describe y el std. 

## REDES BAYESIANAS ##

In [5]:
import pyAgrum as gum

In [6]:
bn = gum.BayesNet() #llama a bayes
print(bn)

BN{nodes: 0, arcs: 0, domainSize: 1, dim: 0}


In [7]:
b,e,j,m,a = [bn.add(name,2)for name in "bejma"]
print(b,e,j,m,a)
print(bn)

0 1 2 3 4
BN{nodes: 5, arcs: 0, domainSize: 32, dim: 10}


In [8]:
bn.addArc(b,a) 
bn.addArc(e,a)
bn.addArc(a,j)
bn.addArc(a,m)

In [9]:
print(bn)

BN{nodes: 5, arcs: 4, domainSize: 32, dim: 20}


In [10]:
bn.cpt(b).fillWith([0.999,0.001]) #false,verdadero

(gum::Potential<double>@0x26b4d9bb650) 
  b                |
0        |1        |
---------|---------|
 0.9990  | 0.0010  |

In [11]:
bn.cpt(e).fillWith([0.998,0.002])

(gum::Potential<double>@0x26b4d9bd110) 
  e                |
0        |1        |
---------|---------|
 0.9980  | 0.0020  |

In [12]:
bn.cpt(a)[{'b':0,'e':0}] = [0.999,0.001]
bn.cpt(a)[{'b':0,'e':1}] = [0.71,0.29]
bn.cpt(a)[{'b':1,'e':0}] = [0.06,0.94]
bn.cpt(a)[{'b':1,'e':1}] = [0.05,0.95]

In [13]:
print(bn.cpt(a))


             ||  a                |
b     |e     ||0        |1        |
------|------||---------|---------|
0     |0     || 0.9990  | 0.0010  |
1     |0     || 0.0600  | 0.9400  |
0     |1     || 0.7100  | 0.2900  |
1     |1     || 0.0500  | 0.9500  |



In [14]:
bn.cpt(j)[{'a':1}] = [0.1,0.9]
bn.cpt(j)[{'a':0}] = [0.95,0.05]
print(bn.cpt(j))


      ||  j                |
a     ||0        |1        |
------||---------|---------|
0     || 0.9500  | 0.0500  |
1     || 0.1000  | 0.9000  |



In [15]:
bn.cpt(m)[{'a':1}] = [0.3,0.7]
bn.cpt(m)[{'a':0}] = [0.99,0.01]
bn.cpt(m)

(gum::Potential<double>@0x26b4d9bdd80) 
      ||  m                |
a     ||0        |1        |
------||---------|---------|
0     || 0.9900  | 0.0100  |
1     || 0.3000  | 0.7000  |

In [16]:
ie = gum.LazyPropagation(bn)

**$P(m)$**

In [17]:
ie.makeInference()
print(ie.posterior(m))


  m                |
0        |1        |
---------|---------|
 0.9883  | 0.0117  |



**$P(+b,-e,+a,-j,+m)$**

In [18]:
#P(+a|+b,-e)
ie.setEvidence({'b':1,'e':0})
ie.makeInference()
Pabe = ie.posterior(a)[1]
Pabe

0.94

In [19]:
#P(-j|+a)
ie.setEvidence({'a':1})
ie.makeInference()
Pja = ie.posterior(j)[0]
Pja

0.1

In [20]:
#P(+m|+a)
ie.setEvidence({'a':1})
ie.makeInference()
Pma = ie.posterior(m)[1]
Pma

0.7

In [21]:
#P(+b)
Pb = bn.cpt(b)[1] #probabilidad definida
Pb

0.001

In [22]:
#P(-e)
Pe = bn.cpt(e)[0]
Pe

0.998

In [23]:
Resultado = Pabe * Pja * Pma * Pb * Pe
print("El resultado es:", Resultado)

El resultado es: 6.56684e-05


**$P(m |+b,+a)$**
## Variables
* H = e,j
* Q = m
* E = b,a

In [24]:
ie.setEvidence({'b':1,'a':1})
ie.makeInference()
ie.posterior(m)

(gum::Potential<double>@0x26b4d9bde80) 
  m                |
0        |1        |
---------|---------|
 0.3000  | 0.7000  |